version: "3.1"
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:${DB_PORT}
    volumes:
      - "./docker/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
