version: "3.1"
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:${DB_PORT}
    volumes:
      - "./db:/var/lib/mysql"
      - "./config/mysql:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   links:
  #     - db
  #   ports:
  #     - 8181:80

  # TODO: Add apache config (like vhosts)
