FROM php:7.4.3-alpine

WORKDIR /app

# Upgrade
RUN apk update \
  && apk upgrade -U -a \
  && docker-php-ext-install pdo pdo_mysql \
  # Setup startup
  && echo "cd /app/dev" > start.sh \
  && echo "php public/socket.php &" >> start.sh \
  && echo "php vendor/bin/doctrine orm:schema-tool:create" >> start.sh \
  && echo "php -S 0.0.0.0:8080 public/index.php" >> start.sh \
  && chmod +x start.sh

EXPOSE 8080
CMD /app/start.sh