version: "3.8"
services:
  db:
    image: mysql
    restart: always
    volumes:
      - "./docker/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  php:
    build: .
    restart: always
    ports:
      - ${HTTP_PORT}:80
