version: "3.8"
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./docker/db:/var/lib/mysql
      - ./config/db:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  fpm:
    build: .
    restart: always
    depends_on:
      - db
  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    restart: always
    depends_on:
      db
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    depends_on:
      - fpm
    ports:
      - ${HTTP_PORT}:80
    environment:
      WEB_PHP_SOCKET: 9000