FROM httpd:alpine

WORKDIR /usr/local/apache2/htdocs

# Add project files
COPY /config ./config

# Upgrade + install driver
RUN apk update \
  && apk upgrade -U -a \
  # Add config files
  && mkdir /usr/local/apache2/conf/conf.d/ \
  && mv -v ./config/apache2/* /usr/local/apache2/conf/conf.d/ \
  && echo "Include /usr/local/apache2/conf/conf.d/*.conf" >> /usr/local/apache2/conf/httpd.conf
