version: "3.8"
services:
  db:
    image: mysql
    restart: always
    # If you want to open ports, uncomment this
    # ports:
    #   - ${DB_PORT}:3306
    volumes:
      - "./docker/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  php:
    build: .
    restart: always
    ports:
      - ${HTTP_PORT}:80
  # Can be usefull when init the db
  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - 80${HTTP_PORT}:80
  #   environment:
  #     - PMA_HOST=${DB_HOST}
  #     - PMA_PORT=${DB_PORT}
