<header>
  <h1>API Documentation</h1>
</header>

<main class="api_main">
  <nav class="api_nav">
    <ul>
      <li><a href="#auth">Auth</a></li>
      <li><a href="#users">Users</a></li>
      <li><a href="#users-groups">Users - Groups</a></li>
      <li><a href="#users-relations">Users - Relations</a></li>
      <li><a href="#users-messages">Users - Messages</a></li>
      <li><a href="#groups">Groups</a></li>
      <li><a href="#groups-members">Groups - Members</a></li>
      <li><a href="#groups-messages">Groups - Messages</a></li>
    </ul>
  </nav>

  <div class="api_doc">
    <p>
      All <i>Returns</i> designate the type of the payload. Each response is a <code>IBaseReponse</code>
    </p>

    <section id="auth">
      <h2>Auth</h2>

      <details class="POST">
        <summary>
          <span class="method">POST</span>
          <code>/auth</code>
        </summary>
        <div class="api_description">
          Get a JWT.
        </div>
        <div class="api_body">
          Body: <code>ILogin</code>
        </div>
        <div class="api_return">
          Returns: <code>IToken</code>
        </div>
      </details>
    </section>

    <section id="users">
      <h2>Users</h2>

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users</code>
        </summary>
        <div class="api_description">
          Get all users
        </div>
        <div class="api_return">
          Returns: <code>IUser[]</code>
        </div>
      </details>

      <details class="POST">
        <summary>
          <span class="method">POST</span>
          <code>/api/users</code>
        </summary>
        <div class="api_description">
          Create a user.
        </div>
        <div class="api_body">
          Body: <code>IUserInput</code>
        </div>
        <div class="api_return">
          Returns: <code>IUser</code>
        </div>
      </details>

      <hr />

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}</code>
        </summary>
        <div class="api_description">
          Get specific user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IUser</code>
        </div>
      </details>
      <details class="auth-locked PUT">
        <summary>
          <span class="method">PUT</span>
          <code>/api/users/{user_id}</code>
        </summary>
        <div class="api_description">
          Update specific user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_body">
          Body: <code>IUserInput</code>
        </div>
        <div class="api_return">
          Returns: <code>IUser</code>
        </div>
      </details>
      <details class="auth-locked DELETE">
        <summary>
          <span class="method">DELETE</span>
          <code>/api/users/{user_id}</code>
        </summary>
        <div class="api_description">
          Delete specific user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IUser</code>
        </div>
      </details>
    </section>

    <section id="users-groups">
      <h2>Users - Groups</h2>

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}/groups</code>
        </summary>
        <div class="api_description">
          Get all groups of a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IGroup[]</code>
        </div>
      </details>

      <details class="auth-locked POST">
        <summary>
          <span class="method">POST</span>
          <code>/api/users/{user_id}/groups</code>
        </summary>
        <div class="api_description">
          Add a group to a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_body">
          Body: <code>IGroupInput</code>
        </div>
        <div class="api_return">
          Returns: <code>IGroup</code>
        </div>
      </details>

      <hr />

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}/groups/{group_id}</code>
        </summary>
        <div class="api_description">
          Get specific user's group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IGroup</code>
        </div>
      </details>
      <details class="auth-locked DELETE">
        <summary>
          <span class="method">DELETE</span>
          <code>/api/users/{user_id}/groups/{group_id}</code>
        </summary>
        <div class="api_description">
          Remove user from group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IBaseResponse</code>
        </div>
      </details>
    </section>

    <section id="users-relations">
      <h2>Users - Relations</h2>

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}/relations</code>
        </summary>
        <div class="api_description">
          Get all relations of a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IRelation[]</code>
        </div>
      </details>

      <details class="auth-locked POST">
        <summary>
          <span class="method">POST</span>
          <code>/api/users/{user_id}/relations</code>
        </summary>
        <div class="api_description">
          Add a relation to a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_body">
          Body: <code>IRelationInput</code>
        </div>
        <div class="api_return">
          Returns: <code>IRelation</code>
        </div>
      </details>

      <hr />

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}/relations/{relation_id}</code>
        </summary>
        <div class="api_description">
          Get specific user relation
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
            <li><code>relation_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IRelation</code>
        </div>
      </details>
      <details class="auth-locked DELETE">
        <summary>
          <span class="method">DELETE</span>
          <code>/api/users/{user_id}/relations/{relation_id}</code>
        </summary>
        <div class="api_description">
          Remove relation of a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
            <li><code>relation_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IBaseResponse</code>
        </div>
      </details>
    </section>

    <section id="users-location">
      <h2>Users - Location</h2>

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}/location</code>
        </summary>
        <div class="api_description">
          Get location of a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>ILocation</code>
        </div>
      </details>
      <details class="auth-locked POST">
        <summary>
          <span class="method">POST</span>
          <code>/api/users/{user_id}/location</code>
        </summary>
        <div class="api_description">
          Add the location of a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_body">
          Body: <code>ILocationInput</code>
        </div>
        <div class="api_return">
          Returns: <code>ILocation</code>
        </div>
      </details>
      <details class="auth-locked PUT">
        <summary>
          <span class="method">PUT</span>
          <code>/api/users/{user_id}/location</code>
        </summary>
        <div class="api_description">
          Update the location of a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_body">
          Body: <code>ILocationInput</code>
        </div>
        <div class="api_return">
          Returns: <code>ILocation</code>
        </div>
      </details>
      <details class="auth-locked DELETE">
        <summary>
          <span class="method">DELETE</span>
          <code>/api/users/{user_id}/location</code>
        </summary>
        <div class="api_description">
          Remove location of a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IBaseResponse</code>
        </div>
      </details>
    </section>

    <section id="users-messages">
      <h2>User - Messages</h2>

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}/messages</code>
        </summary>
        <div class="api_description">
          Get all messages who concern a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IMessage[]</code>
        </div>
      </details>

      <hr />

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/users/{user_id}/messages/{message_id}</code>
        </summary>
        <div class="api_description">
          Get specific message who concern a user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
            <li><code>message_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IMessage</code>
        </div>
      </details>
    </section>

    <section id="groups">
      <h2>Groups</h2>

      <!--
      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/groups</code>
        </summary>
        <div class="api_description">
          Get all groups
        </div>
        <div class="api_return">
          Returns: <code>IGroup[]</code>
        </div>
      </details>
      -->

      <details class="auth-locked POST">
        <summary>
          <span class="method">POST</span>
          <code>/api/groups</code>
        </summary>
        <div class="api_description">
          Create a group
        </div>
        <div class="api_body">
          Body: <code>IGroupInput</code>
        </div>
        <div class="api_return">
          Returns: <code>IGroup</code>
        </div>
      </details>

      <hr />

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/groups/{group_id}</code>
        </summary>
        <div class="api_description">
          Get specific group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IGroup</code>
        </div>
      </details>
      <details class="auth-locked PUT">
        <summary>
          <span class="method">PUT</span>
          <code>/api/groups/{group_id}</code>
        </summary>
        <div class="api_description">
          Update a specific group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_body">
          Body: <code>IGroupInput</code>
        </div>
        <div class="api_return">
          Returns: <code>IGroup</code>
        </div>
      </details>
      <details class="auth-locked DELETE">
        <summary>
          <span class="method">DELETE</span>
          <code>/api/groups/{group_id}</code>
        </summary>
        <div class="api_description">
          Delete a group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IBaseResponse</code>
        </div>
      </details>
    </section>

    <section id="groups-members">
      <h2>Groups - Members</h2>

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/groups/{group_id}/members</code>
        </summary>
        <div class="api_description">
          Get all group's members
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IUser[]</code>
        </div>
      </details>

      <hr />

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/groups/{group_id}/members/{user_id}</code>
        </summary>
        <div class="api_description">
          Get specific group's user
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IUser</code>
        </div>
      </details>
      <details class="auth-locked DELETE">
        <summary>
          <span class="method">DELETE</span>
          <code>/api/groups/{group_id}/members/{user_id}</code>
        </summary>
        <div class="api_description">
          Remove a user from a group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
            <li><code>user_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IBaseResponse</code>
        </div>
      </details>
    </section>

    <section id="groups-messages">
      <h2>Groups - Messages</h2>

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/groups/{group_id}/messages</code>
        </summary>
        <div class="api_description">
          Get all messages of a group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IMessage[]</code>
        </div>
      </details>

      <hr />

      <details class="auth-locked GET">
        <summary>
          <span class="method">GET</span>
          <code>/api/groups/{group_id}/messages/{message_id}</code>
        </summary>
        <div class="api_description">
          Get specific message of a group
        </div>
        <div class="api_params">
          Params:
          <ul>
            <li><code>group_id</code>: <code>/[0-9]+/</code></li>
            <li><code>message_id</code>: <code>/[0-9]+/</code></li>
          </ul>
        </div>
        <div class="api_return">
          Returns: <code>IMessage</code>
        </div>
      </details>
    </section>
  </div>

  <aside class="api_types">
    <h2>API Types</h2>
    <details>
      <summary>
        <code>IAPIResult</code>
      </summary>
      <code>
        <pre>string 
  | IToken 
  | IUser | IUser[] 
  | IGroup | IGroup[] 
  | IRelation | IRelation[] 
  | ILocation 
  | IMessage | IMessage[]</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IBaseReponse</code>
      </summary>
      <code>
        <pre>{
  status: number,
  payload: IAPIResult
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>ILogin</code>
      </summary>
      <code>
        <pre>{
  username: string,
  password: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IToken</code>
      </summary>
      <code>
        <pre>{
  token: string,
  created_at: string,
  expires: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>EStatus</code>
      </summary>
      <code>
        <pre>{
  SAFE = 0,
  UNSAFE
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IUser</code>
      </summary>
      <code>
        <pre>{
  id: number,
  username: string,
  email: string,
  phone: string | number,
  birthdate: string,
  address: string,
  city: string,
  country: string,
  status: EStatus,
  created_at: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IUserInput</code>
      </summary>
      <code>
        <pre>{
    username: string,
    password: string,
    email: string,
    phone: string,
    birthdate: string,
    address: string,
    city: string,
    country: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IGroup</code>
      </summary>
      <code>
        <pre>{
  id: number,
  name: string,
  owner: IUser,
  members: IUser[],
  messages: IMessage[],
  created_at: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IGroupInput</code>
      </summary>
      <code>
        <pre>{
  name: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IRelation</code>
      </summary>
      <code>
        <pre>{
  id: number,
  sender: IUser,
  target: IUser,
  created_at: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IRelationInput</code>
      </summary>
      <code>
        <pre>{
  target: number
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>ILocation</code>
      </summary>
      <code>
        <pre>{
  id: number,
  long: number,
  lat: number,
  user: IUser,
  updated_at: string
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>ILocationInput</code>
      </summary>
      <code>
        <pre>{
  long: number,
  lat: number
}</pre>
      </code>
    </details>

    <details>
      <summary>
        <code>IMessage</code>
      </summary>
      <code>
        <pre>{
  id: number,
  content: string,
  sender: IUser,
  target?: IUser,
  created_at: string
  updated_at: string
}</pre>
      </code>
    </details>
  </aside>
</main>

<footer></footer>