<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<div id="board">
  <form action="">
    <input type="text" placeholder="publication">
    <input type="submit" value="publish">
  </form>

  <div class="publications">

    <div class="publication">
      <div class="content">Y a le covid!</div>
      <div class="side">
        <div class="author">Julien</div>
        <div class="created-at">19/10/21</div>
      </div>
    </div>

  </div>
</div>