<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<header>
  <nav>
    <ul>
      <li><a href="">Account</a></li>
      <li><a href="">Search</a></li>
      <li><a href="board">Board</a></li>
      <li><a href="">Groups</a></li>
      <li><a href="messages">Messages</a></li>
      <li><a href="">Map</a></li>
      <li><a href="">Settings</a></li>
    </ul>
  </nav>
</header>

<main  id="board">

<form action="">
    <input type="text" placeholder="publication">
    <input type="submit" value="publish">
</form>

<div class="publications">
    
    <div class="publication">
        <div class="content">Y a le covid!</div>
        <div class="side">
            <div class="author">Julien</div>
            <div class="created-at">19/10/21</div>
        </div>
    </div>

</div>


</main>

<footer></footer>