<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<header>
  <h1>Signin</h1>
</header>

<main>
  <p>Need account ? <a href="signup.php">Go signup</a></p>
  <form class="grid-form" action="authentificate.php" method="post">
    <input type="text" name="login" id="login" placeholder="Login">
    <input type="password" name="password" id="password" placeholder="password">
    <input class="form-button" type="submit" value="Signin">
  </form>
  <!-- PHP: wrong login or password -->
  <?php if (!empty($_SESSION['message'])) : ?>
    <div class="message">
      <?= $_SESSION['message']; ?>
    </div>
  <?php endif; ?>
  <p class="link-center"><a href="formpassword.php">I forgot my password</a></p>
</main>

<footer></footer>
