<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />


  <!-- Meta Data -->
  <title>Signin</title>
  <meta name="description" content="" />
  <!-- Critical style -->
  <style>
    * {
      box-sizing: border-box;
    }

    html,
    body {
      margin: 0;
      padding: 0;
      height: 100%;
      width: 100%;
    }
  </style>

  <!-- Style -->
  <link rel="stylesheet" href="/static/css/style.css" />

  <meta name="viewport" content="initial-scale=1" />
</head>

<body class="body-flex">
  <header>
    <h1>Signin</h1>
  </header>

  <main>
    <p>Need account ? <a href="signup.php">Go signup</a></p>
    <form class="grid-form" action="authentificate.php" method="post">
      <input type="text" name="login" id="login" placeholder="Login">
      <input type="password" name="password" id="password" placeholder="password">
      <input class="form-button" type="submit" value="Signin">
    </form>
    <!-- PHP: wrong login or password -->
    <?php if (!empty($_SESSION['message'])): ?>
      <div class="message">
        <?= $_SESSION['message'];?>
      </div>
    <?php endif; ?>
    <p class="link-center"><a href="formpassword.php">I forgot my password</a></p>
  </main>

  <footer></footer>

  <!-- JS -->
  <script>
    window.env = {
      PHP_MODE: '<?= $_ENV['PHP_ENV'] ?>',
    }
  </script>
  <script src="/static/js/bundle.js" defer></script>
</body>

</html>