<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />

  <!-- Meta Data -->
  <title></title>
  <meta name="description" content="" />
  <!-- Critical style -->
  <style>
    * {
      box-sizing: border-box;
    }

    html,
    body {
      margin: 0;
      padding: 0;
      height: 100%;
      width: 100%;
    }
  </style>

  <!-- Style -->
  <link rel="stylesheet" href="/static/css/style.css" />

  <meta name="viewport" content="initial-scale=1" />
</head>

<body>
  <header>
    <h1>Hello World</h1>
  </header>

  <main>
    <p>
      With hot-reload on PHP !
    </p>
  </main>

  <footer></footer>

  <!-- JS -->
  <script>
    window.env = {
      PHP_MODE: '<?= $_ENV['PHP_ENV'] ?>',
    }
  </script>
  <script src="/static/js/bundle.js" defer></script>
</body>

</html>