<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<header>
  <h1>Signin</h1>
</header>

<main>
  <p>Need account ? <a href="register">Go signup</a></p>
  <form id="login-form" class="grid-form">
    <input type="text" name="username" id="login" placeholder="Login">
    <input type="password" name="password" id="password" placeholder="password">
    <input class="form-button" type="submit" value="Signin">
  </form>
  <div id="login-result" class="message">
  </div>
  <p class="link-center"><a href="formpassword">I forgot my password</a></p>
</main>

<footer></footer>