<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<div class="signin">
  <p>Need account ? <a href="register">Go signup</a></p>
  <form id="login-form" class="grid-form">
    <input type="text" name="username" id="username" placeholder="Username">
    <input type="password" name="password" id="password" placeholder="password">
    <input class="form-button" type="submit" value="Signin">
  </form>
  <div id="signin-result" class="message">
  </div>
  <p class="link-center"><a href="formpassword">I forgot my password</a></p>
</div>