<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<div class="signin">
  <p>Need account ? <a href="register">Go signup</a></p>
  <form id="login-form" class="grid-form">
    <div class="field">
      <input type="text" name="username" id="username" placeholder=" ">
      <label for="username">
        Username
      </label>
    </div>
    <div class="field">
      <input type="password" name="password" id="password" placeholder=" ">
      <label for="password">
        Password
      </label>
    </div>
    <input class="form-button" type="submit" value="Signin">
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
  </form>
  <div id="signin-result" class="message">
  </div>
  <p class="link-center"><a href="formpassword">I forgot my password</a></p>
</div>