<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="UTF-8" />


	<!-- Meta Data -->
	<title>Crisis - <?= $title ?></title>
	<meta name="description" content="" />
	<!-- Critical style -->
	<style>
		* {
			box-sizing: border-box;
		}

		html,
		body {
			margin: 0;
			padding: 0;
			height: 100%;
			width: 100%;
		}
	</style>

	<!-- Style -->
	<link rel="stylesheet" href="/static/css/style.css" />

	<meta name="viewport" content="initial-scale=1" />
</head>

<body>
	<header>
		<?php if (!$nonav) : ?>
			<nav>
				<ul>
					<li><a href="/account">Account</a></li>
					<li><a href="">Search</a></li>
					<li><a href="board">Board</a></li>
					<li><a href="">Groups</a></li>
					<li><a href="/messages">Messages</a></li>
					<li><a href="/map">Map</a></li>
					<li><a href="">Settings</a></li>
				</ul>
			</nav>
		<?php endif ?>
	</header>

	<main>
		<?= $content ?>
	</main>

	<footer></footer>

	<!-- JS -->
	<script>
		window.env = {
			PHP_MODE: '<?= $_ENV['PHP_ENV'] ?>',
		}
	</script>
	<script src="/static/js/bundle.js" defer></script>
</body>

</html>