<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<h1>Map</h1>

<!-- TODO DIRTY-->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />
<style>
  #mapid {
    height: 480px;
    width: 720px;
  }
</style>

<div id="mapid"></div>