<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<div class="messages">
    <section class="conversations">
        <div class="conversation">
            <div class="name">Jean-Michel</div>
            <div class="last-message side">Bonjour</div>
        </div>
    </section>

    <div class="conversation-focus">
        <div class="conversation-messages">
            <div class="message">
                <div class="content">Bonjour</div>
                <div class="side">
                    <div class="name">Jean-Michel</div>
                    <div class="send-at">19/10/21</div>
                </div>
            </div>
            <div class="message my-message">
                <div class="content"> Bonjour</div>
                <div class="side">
                    <div class="name">Julien</div>
                    <div class="send-at">19/10/21</div>
                </div>
            </div>
        </div>
        <form action="" id="message-form">
            <input type="text" name="new-message" id="new-message" placeholder="Write here your message">
            <input class="send-new-message" type="submit" value="Send">
        </form>
    </div>
</div>