<?php
// This is a partial HTML file, it will be included in `layout.php` via the var $content
?>

<header>
  <nav>
    <ul>
      <li><a href="/account">Account</a></li>
      <li><a href="">Search</a></li>
      <li><a href="board">Board</a></li>
      <li><a href="">Groups</a></li>
      <li><a href="messages">Messages</a></li>
      <li><a href="">Map</a></li>
      <li><a href="">Settings</a></li>
    </ul>
  </nav>
</header>

<main id="welcome">
  <div>
    Hello
    <div id="name"></div>
  </div>

  <p>Want to change you password ? <a href="">Here</a></p>
  <p>Remove your account <a href="">Delete account</a></p>

  <p>Signout</p>

</main>

<footer></footer>