#docker-compose --env-file .env.dev -f "docker-compose.dev.yml" up -d --build
version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - "../docker/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  php:
    build: .
    volume:
      - ..:/workspace:cached
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8085:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
