on:
  push:
    branches: ["release"]

jobs:
  publish:
    runs-on: docker-dind
    name: "Publish on the developement server"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Adding Dev Server to known hosts
        run: mkdir --parents $HOME/.ssh && ssh-keyscan -H ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: Create Docker Context
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST }}
          context_name: "dev-server"
          ssh_key: ${{ secrets.SSH_KEY }}
          use_context: true

      - name: Build docker-compose
        run: docker-compose --H ${{ secrets.SSH_HOST }} up --d --build
